# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e40002e0bfd2d130d0356cfd7b282c8"
name = "fin-new"
handle = "fin-new"
application_url = "https://example.com/"
embedded = true

[build]
dev_store_url = "helge-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
